### ISSUE TITLE
Paddock grouping duplication attribution

### ISSUE THREAD

**Issue by haydew** [FarmBuild/farmbuild-web-mapping#3]
Paddock grouping is writing duplicate paddock ids under the json farmdata structure. Please see json after exporting grouped paddocks. Earlier versions of farmbuild mapping did not have this issue.
`"paddockGroups": [
    {
      "name": "Business Default Group 1",
      "paddocks": [
        "Paddock 1465447173180",
        "Paddock 1465447173180",
        "Paddock 1465447181640",
        "Paddock 1465447173180",
        "Paddock 1465447173180"
      ]
    },
    {
      "name": "Business Default Group 2",
      "paddocks": [
        "Paddock 1465447181640",
        "Paddock 1465447181640"
      ]`

**Comment by hiroki-gota** [comment]
Hayden,

We've fixed the duplicated paddock names and pushed the release.

Please verify.
